spring:
  datasource:
#    url: jdbc:mysql://edu-test-db1.cc1ughusgul3.ap-northeast-2.rds.amazonaws.com:3306/edu_test
#    username: admin
#    password: aton4273!
#    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mariadb://127.0.0.1:3306/edu_test
    username: root
    password: ajdcjddl2
    driver-class-name: org.mariadb.jdbc.Driver
  mvc:
    view:
      prefix: /WEB-INF/views/
      suffix: .jsp

mybatis:
  type-aliases-package: com.example.demo.dto
  mapper-locations: classpath:mappers/*.xml
  