spring:
  mvc:
    view:
      suffix: .html
  datasource:
    url: jdbc:mariadb://127.0.0.1:3306/pass
    username: root
    password: ajdcjddl2
    driver-class-name: org.mariadb.jdbc.Driver
  thymeleaf:
    prefix: classpath:/templates/

mybatis:
  type-aliases-package: com.example.pass.dto
  mapper-locations: classpath:mappers/*.xml

url:
#  authUrl : https://api-stg.passauth.co.kr/v1/certification/notice
  authUrl : http://localhost:8081/api-stg.passauth.co.kr/v1/certification/notice
#  resultUrl : https://api-stg.passauth.co.kr/certification/result
  resultUrl : http://localhost:8081/api-stg.passauth.co.kr/certification/result
  bear : AT-111111

info:
  Tycd : S2001
  companyCd : 90001