spring:
  datasource:
    url: jdbc:mariadb://127.0.0.1:3306/api_server
    username: root
    password: ajdcjddl2
    driver-class-name: org.mariadb.jdbc.Driver

mybatis:
  type-aliases-package: com.example.apiserver.dto
  mapper-locations: classpath:mappers/*.xml

server:
  port: 8081

body:
  auth-request:
    companyCd
    ,serviceTycd
    ,telcoTycd
    ,phoneNo
    ,userNm
    ,birthday
    ,gender
    ,reqTitle
    ,reqCSPhoneNo
    ,reqEndDttm
    ,signTargetTycd
    ,signTarget
    ,companyCd
    ,serviceTycd
    ,telcoTycd
    ,phoneNo
    ,userNm
    ,birthday
    ,gender
    ,reqTitle
    ,reqCSPhoneNo
    ,reqEndDttm
    ,signTargetTycd
    ,signTarget
  result-request:
    companyCd
    ,reqTxId
    ,certTxId
    ,phoneNo
    ,userNm