spring:
  datasource:
    url: jdbc:log4jdbc:mysql://localhost:3307/final_project
#    url: jdbc:mysql://localhost:3307/final_project
    username: root
    password: ajdcjddl2
    driver-class-name: net.sf.log4jdbc.sql.jdbcapi.DriverSpy
#    driver-class-name: com.mysql.cj.jdbc.Driver
  mail:
    host: smtp.dooray.com
    port: 587
    username: passlogin@atoncorp.com
    password: ats4273*
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

# session time out 설정
server:
  servlet:
    session:
      timeout: 8000 # 초 단위

mybatis:
  type-aliases-package: com.example.finalproject.dto
  mapper-locations: classpath:mappers/*.xml