spring:
  datasource:
    url: jdbc:mysql://localhost:3307/final_project
    username: root
    password: ajdcjddl2
    driver-class-name: com.mysql.cj.jdbc.Driver

mybatis:
  type-aliases-package: com.example.finalproject.dto
  mapper-locations: classpath:mappers/*.xml

# logback 파일 위치 설정
#logging:
#  config: classpath:logback.xml
#server:
#  servlet:
#    session:
#      timeout: 10
