spring:
  datasource:
    url: jdbc:log4jdbc:mysql://localhost:3307/final_project
#    url: jdbc:mysql://localhost:3307/final_project
    username: root
    password: ajdcjddl2
    driver-class-name: net.sf.log4jdbc.sql.jdbcapi.DriverSpy
#    driver-class-name: com.mysql.cj.jdbc.Driver
  mail:
    host: smtp.dooray.com
    port: 587
    username: passlogin@atoncorp.com
    password: ats4273*
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true


server:
  servlet:
    session: # session time out 설정
      timeout: 600 # 초 단위
  error:
    whitelabel:
      enabled: false # 기본 whitelabel page 사용 안함.
    path: /error # 에러 발생시 이동할 경로

mybatis:
  type-aliases-package: com.example.finalproject.dto
  mapper-locations: classpath:mappers/*.xml